//
//  LoginPresenter.swift
//  TwitterPosts
//
//  Created by Alex Cuello ortiz on 17/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol LoginPresenterInput {
    
}

protocol LoginPresenterOutput: class {
    
}

class LoginPresenter: LoginPresenterInput {
    
    weak var output: LoginPresenterOutput?
    
    // MARK: Presentation logic
    
}
