//
//  TweetsTimelinePresenter.swift
//  TwitterPosts
//
//  Created by Alex Cuello ortiz on 17/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol TweetsTimelinePresenterInput {
    func presentTweets(response: TweetsTimelineScene.GetTweetsTimeline.Response)
}

protocol TweetsTimelinePresenterOutput: class {
    func displayTweetsTimeline(viewModel: TweetsTimelineScene.GetTweetsTimeline.ViewModel)
}

class TweetsTimelinePresenter: TweetsTimelinePresenterInput {
    
    weak var output: TweetsTimelinePresenterOutput?
    
    // MARK: Presentation logic
    func presentTweets(response: TweetsTimelineScene.GetTweetsTimeline.Response) {
        
        var displayTweets:[TweetsTimelineScene.GetTweetsTimeline.DisplayTweet] = []
        for tweet in response.tweetsTimeline {
            let user = tweet.user
            let displayUser = TweetsTimelineScene.GetTweetsTimeline.DisplayUser(id: user.id, name: user.name, screenName: user.screenName, profileImageURL: user.profileImageURL)
            let displayTweet = TweetsTimelineScene.GetTweetsTimeline.DisplayTweet(id: tweet.id, creationDate: tweet.creationDate, text: tweet.text, user: displayUser, favourite: tweet.favourite)
            displayTweets.append(displayTweet)
        }
        let viewModel = TweetsTimelineScene.GetTweetsTimeline.ViewModel(displayTweets: displayTweets)
        self.output?.displayTweetsTimeline(viewModel: viewModel)
    }
}
