//
//  TweetsTimelineRouter.swift
//  TwitterPosts
//
//  Created by Alex Cuello ortiz on 17/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol TweetsTimelineRouterInput {
    
}

protocol TweetsTimelineRouterDataSource: class {
    
}

protocol TweetsTimelineRouterDataDestination: class {
    
}

class TweetsTimelineRouter: TweetsTimelineRouterInput {
    
    weak var viewController: TweetsTimelineViewController!
    weak private var dataSource: TweetsTimelineRouterDataSource!
    weak var dataDestination: TweetsTimelineRouterDataDestination!
    
    init(viewController: TweetsTimelineViewController, dataSource: TweetsTimelineRouterDataSource, dataDestination: TweetsTimelineRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
