//
//  TweetsTimelineModels.swift
//  TwitterPosts
//
//  Created by Alex Cuello ortiz on 17/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

import Foundation

struct TweetsTimelineScene {
    
    struct GetTweetsTimeline {
        
        struct Request {
            var page: Int
        }
        
        struct Response {
            var tweetsTimeline: [Tweet]
//            var error: TwitterStoreError?
        }
        
        struct ViewModel {
            var displayTweets: [DisplayTweet]
//            var error: TwitterStoreError?
        }
        
        struct DisplayTweet {
            var id: String
            var creationDate: String
            var text: String
            var user: DisplayUser
            var favourite:Bool
        }
        
        struct DisplayUser {
            var id: String
            var name: String
            var screenName: String
            var profileImageURL: String
        }
    }
    
    struct SetSelectedUser {
        
        struct Request {
            let index: Int
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
}
