//
//  TweetsTimelineConfigurator.swift
//  TwitterPosts
//
//  Created by Alex Cuello ortiz on 17/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension TweetsTimelineInteractor: TweetsTimelineViewControllerOutput, TweetsTimelineRouterDataSource, TweetsTimelineRouterDataDestination {
}

extension TweetsTimelinePresenter: TweetsTimelineInteractorOutput {
}

class TweetsTimelineConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = TweetsTimelineConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: TweetsTimelineViewController) {
        
        let presenter = TweetsTimelinePresenter()
        presenter.output = viewController
        
        let interactor = TweetsTimelineInteractor()
        interactor.output = presenter
        
        let router = TweetsTimelineRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
