//
//  TweetsTimelineRouter.swift
//  TwitterPosts
//
//  Created by Alex Cuello ortiz on 17/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol TweetsTimelineRouterInput {
    
}

protocol TweetsTimelineRouterDataSource: class {
    var selectedUser: User! {get set}
}

protocol TweetsTimelineRouterDataDestination: class {
    
}

class TweetsTimelineRouter: TweetsTimelineRouterInput {
    
    weak var viewController: TweetsTimelineViewController!
    weak private var dataSource: TweetsTimelineRouterDataSource!
    weak var dataDestination: TweetsTimelineRouterDataDestination!
    
    struct SegueIdentifiers {
        static let userProfile = "userProfile"
    }
    
    init(viewController: TweetsTimelineViewController, dataSource: TweetsTimelineRouterDataSource, dataDestination: TweetsTimelineRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    func navigateToUserProfileScene()
    {
        viewController.performSegue(withIdentifier: SegueIdentifiers.userProfile, sender: viewController)
    }
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
        guard let segueIdentifier = segue.identifier else {
            return
        }
        
        switch segueIdentifier {
        case SegueIdentifiers.userProfile:
            passDataToUserProfileScene(for: segue)
        default:
            return
        }
    }
    
    // MARK: Communication
    
    func passDataToUserProfileScene(for segue: UIStoryboardSegue)
    {
        // NOTE: Teach the router how to pass data to the next scene
        
        if let userProfileViewController = segue.destination as? UserProfileViewController {
            userProfileViewController.router?.dataDestination.user = dataSource.selectedUser
        }
    }
}
