//
//  UserProfileRouter.swift
//  TwitterPosts
//
//  Created by Alex Cuello ortiz on 17/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol UserProfileRouterInput {
    
}

protocol UserProfileRouterDataSource: class {
    
}

protocol UserProfileRouterDataDestination: class {
    var user: User! {get set}
}

class UserProfileRouter: UserProfileRouterInput {
    
    weak var viewController: UserProfileViewController!
    weak private var dataSource: UserProfileRouterDataSource!
    weak var dataDestination: UserProfileRouterDataDestination!
    
    init(viewController: UserProfileViewController, dataSource: UserProfileRouterDataSource, dataDestination: UserProfileRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
