//
//  UserProfileInteractor.swift
//  TwitterPosts
//
//  Created by Alex Cuello ortiz on 17/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol UserProfileInteractorInput {
    func getUserDetails(request: UserProfileScene.PresentUser.Request)
}

protocol UserProfileInteractorOutput {
    func presentUserDetails(response: UserProfileScene.PresentUser.Response)
}

protocol UserProfileDataSource {
    
}

protocol UserProfileDataDestination {
    var user: User! {get set}
}

class UserProfileInteractor: UserProfileInteractorInput, UserProfileDataSource, UserProfileDataDestination {
    
    var output: UserProfileInteractorOutput?
    
    // MARK: Business logic
    var user: User!

    func getUserDetails(request: UserProfileScene.PresentUser.Request) {
        let response = UserProfileScene.PresentUser.Response(user: self.user)
        self.output?.presentUserDetails(response: response)
    }

}
