//
//  UserProfileModels.swift
//  TwitterPosts
//
//  Created by Alex Cuello ortiz on 17/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct UserProfileScene {
    
    struct PresentUser {
        
        struct Request {
            
        }
        
        struct Response {
            var user:User
        }
        
        struct ViewModel {
            var displayUser:UserProfileScene.DisplayUser
        }
    }
    
    struct DisplayUser {
        var id: String
        var name: String
        var screenName: String
        var description: String
        var profileImageURL: String
        var profileBackgroundImageURL: String
        var location: String
        var followers: Int64
        var following: Int64
    }
    
}
