//
//  UserProfilePresenter.swift
//  TwitterPosts
//
//  Created by Alex Cuello ortiz on 17/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol UserProfilePresenterInput {
    func presentUserDetails(response: UserProfileScene.PresentUser.Response)
}

protocol UserProfilePresenterOutput: class {
    func displayUserDetails(viewModel: UserProfileScene.PresentUser.ViewModel)
}

class UserProfilePresenter: UserProfilePresenterInput {
    
    weak var output: UserProfilePresenterOutput?
    
    // MARK: Presentation logic
    func presentUserDetails(response: UserProfileScene.PresentUser.Response) {
        let user = response.user
        let displayUser = UserProfileScene.DisplayUser(id: user.id, name: user.name, screenName: user.screenName, description: user.description, profileImageURL: user.profileImageURL, profileBackgroundImageURL: user.profileBackgroundImageURL, location: user.location, followers: user.followers, following: user.following)
        let viewModel = UserProfileScene.PresentUser.ViewModel(displayUser: displayUser)
        self.output?.displayUserDetails(viewModel: viewModel)
    }
}
