//
//  UserProfileConfigurator.swift
//  TwitterPosts
//
//  Created by Alex Cuello ortiz on 17/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension UserProfileInteractor: UserProfileViewControllerOutput, UserProfileRouterDataSource, UserProfileRouterDataDestination {
}

extension UserProfilePresenter: UserProfileInteractorOutput {
}

class UserProfileConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = UserProfileConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: UserProfileViewController) {
        
        let presenter = UserProfilePresenter()
        presenter.output = viewController
        
        let interactor = UserProfileInteractor()
        interactor.output = presenter
        
        let router = UserProfileRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
